### ISSUE TITLE
Inconsistency in sign of detections

### ISSUE THREAD

**Issue by Etomer** [Etomer/structure-from-sound-python#10]
Double check that the sign of the detections has the appropriate signs. Currently `tdoa_for_python.m` has to flip the sign of the tdoa_vector. i.e. is $d_{ij} = |r_i - s| - |r_j - s|$ or $d_{ij} = -|r_i - s| + |r_j - s|$

**Comment by maltelarsson2** [comment]
See commit b8a7a0f
