### ISSUE TITLE
Evaluation of different steps of system

### ISSUE THREAD

**Issue by Etomer** [Etomer/structure-from-sound-python#6]
Create some basic evaluation metric for different steps of the system (for data where there is ground truth):

- [ ] Detections (outlier ratio and error std; speed)
- [ ] Tdoa-vector (error std and outlier ratio, as a function of input noise and outliers; speed)
- [ ] Final positions (percentage of trajectory recovered, error std; speed)

These are some ideas of evaluation metric but there probably are better metric.

**Comment by maltelarsson2** [comment]
Can be iterated further with more improved plots, but the basic functionality is there
